### ISSUE TITLE
Formalised Parallelism: Join Calculus, Transactional Events

### ISSUE THREAD

**Issue by sirinath** [vrtbl/passerine#23] opened 2021-02-23 06:36 UTC
Perhaps you can investigate possibility of incorporating features from Transactional Events, Join Calculus and Concurrent ML.

Following are some pointers:

# CML

- http://cml.cs.uchicago.edu/
- https://github.com/Hopac/Hopac
- https://github.com/Hopac/Hopac.Extras

# Join Calculus

- https://github.com/Chymyst/chymyst-core, http://chemist.io/
- https://github.com/polytypic/JoinCML
- http://tryjoinads.org/
- http://jocaml.inria.fr/
- http://join.inria.fr/eng.htm
- https://sites.google.com/site/winitzki/tutorial-on-join-calculus-and-its-implementation-in-ocaml-jocaml
- http://moscova.inria.fr/join/index.shtml
- https://github.com/phaller/ScalaJoins
- https://github.com/Jiansen/ScalaJoin

# Transactional Events

- https://wasp.cs.washington.edu/tecaml/
- https://www.cs.rit.edu/~mtf/research/tx-events/

**Comment by slightknack** [comment] 2021-02-24 10:26
Thanks for the long list of papers and associated links. I'll try to work through them, but I'm pretty busy. Would you mind summarizing the main ideas and how they relate to Passerine? Thanks!

**Comment by sirinath** [comment] 2021-02-25 04:33
Since much of the work in JC & TE is still research state and Passerine is early stage how it can be use is not clear cut. This will need some research to figure out. But main request is a formal and verifiable model for parallel code.

**Comment by slightknack** [comment] 2021-03-29 08:13
I think that modeling parallelism through algebraic effects is a simple and effective way to guarantee asynchronous code works as intended. I think Passerine's existing concurrency model is strong enough to model certain behavior guarantees. Because the research surrounding these topics is still brand-new, and I don't see any immediate application it has for Passerine, I'm going to close this issue now. If you'd like to open another issue discussing fiber-based concurrency and algebraic effects so we can move towards an implementation, please do 😄

**Closed by slightknack** 2021-03-29 08:13 UTC
Labels: feature, question
